### ISSUE TITLE
zoom/rotation as props

### ISSUE THREAD

**Issue by mouhsinelonly** [mgorabbani/react-image-pan-zoom-rotate#14]
it would be better to enable passing rotation/zoom/toolbar
 as props in case we want to add a custom control icons

      <ReactPanZoom image="https://drscdn.500px.org/photo/105738331/q%3D80_m%3D2000/v2?webp=true&sig=538a4f76f4966c84acb01426bb4a4a5e4a85b72a2c3bd64973d3a369f9653007" alt="document image" rotation={90} zoom={1} toolbar={false} />

**Comment by mgorabbani** [comment]
now you can do it! check example folder or codesandbox
