### ISSUE TITLE
create a reset zoom button

### ISSUE THREAD

**Issue by roger-swipejobs** [mgorabbani/react-image-pan-zoom-rotate#24]
An extra button to reset to initial zoom and align position could be added

**Comment by roger-swipejobs** [comment]
Hello, any idea if this feature would be considered in future releases? thanks

**Comment by mgorabbani** [comment]
Hi I am planning to clean up the project as the dependencies are outdated. after that I will try to add it. you're welcome to give a PR as well.

**Comment by mgorabbani** [comment]
@roger-swipejobs feature added! 🚀
